import fs from 'node:fs/promises'
import { readPositions, readPrices, GENERATED_FILE } from './positions-shared'

async function main() {
  const [positions, prices] = await Promise.all([readPositions(), readPrices()])

  const out: any[] = []
  const missing: string[] = []

  for (const { id, data } of positions) {
    if (data.kind === 'stock') {
      const lock = prices[id]
      if (!lock?.entryPrice) {
        missing.push(`${id} (stock entry)`)
        continue
      }
      out.push({
        kind: 'stock',
        id,
        symbol: data.symbol,
        name: data.name ?? data.symbol,
        entryPrice: lock.entryPrice,
        entryDate: data.entryDate,
        ...(lock.exitPrice != null ? { exitPrice: lock.exitPrice } : {}),
        ...(data.exitDate ? { exitDate: data.exitDate } : {}),
      })
    } else if (data.kind === 'crypto') {
      const lock = prices[id]
      if (!lock?.entryPrice) {
        missing.push(`${id} (crypto entry)`)
        continue
      }
      out.push({
        kind: 'crypto',
        id,
        symbol: data.symbol,
        coingeckoId: data.coingeckoId,
        name: data.name ?? data.symbol,
        entryPrice: lock.entryPrice,
        entryDate: data.entryDate,
        ...(lock.exitPrice != null ? { exitPrice: lock.exitPrice } : {}),
        ...(data.exitDate ? { exitDate: data.exitDate } : {}),
      })
    } else if (data.kind === 'private') {
      if (data.entryValuation == null || data.currentValuation == null) {
        missing.push(`${id} (private valuations)`)
        continue
      }
      out.push({
        kind: 'private',
        id,
        name: data.name,
        entryValuation: data.entryValuation,
        currentValuation: data.currentValuation,
        entryDate: data.entryDate,
        ...(data.exitValuation != null ? { exitValuation: data.exitValuation } : {}),
        ...(data.exitDate ? { exitDate: data.exitDate } : {}),
      })
    }
  }

  out.sort((a, b) => (a.entryDate < b.entryDate ? 1 : -1))

  const code =
    `// generated by scripts/build-positions.ts — do not edit\n` +
    `import type { Position } from './types'\n\n` +
    `export const positions: Position[] = ${JSON.stringify(out, null, 2)}\n`
  await fs.writeFile(GENERATED_FILE, code)

  if (missing.length > 0) {
    console.warn(`! ${missing.length} position(s) missing prices — run \`bun run prices:resolve\`:`)
    for (const m of missing) console.warn(`  - ${m}`)
  }
  console.log(`✓ generated ${out.length} position(s)`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
