import fs from 'node:fs/promises'
import { readPositions, readPrices, findEventDate, GENERATED_FILE } from './positions-shared'

async function main() {
  const [positions, prices] = await Promise.all([readPositions(), readPrices()])

  const out: any[] = []
  const missing: string[] = []

  for (const { id, data, introHtml, events } of positions) {
    const entryDate = findEventDate(events, 'entry')
    const exitDate = findEventDate(events, 'exit')
    if (!entryDate) {
      missing.push(`${id}: no entry event`)
      continue
    }

    const eventsOut = events.map((e) => ({ date: e.date, kind: e.kind, tldr: e.tldr, html: e.html }))
    const common = {
      id,
      ...(introHtml ? { intro: introHtml } : {}),
      events: eventsOut,
      entryDate,
      ...(exitDate ? { exitDate } : {}),
    }

    if (data.kind === 'stock') {
      const lock = prices[id]
      if (!lock?.entryPrice) {
        missing.push(`${id} (stock entry price)`)
        continue
      }
      out.push({
        ...common,
        kind: 'stock',
        symbol: data.symbol,
        name: data.name ?? data.symbol,
        entryPrice: lock.entryPrice,
        ...(lock.exitPrice != null ? { exitPrice: lock.exitPrice } : {}),
      })
    } else if (data.kind === 'crypto') {
      const lock = prices[id]
      if (!lock?.entryPrice) {
        missing.push(`${id} (crypto entry price)`)
        continue
      }
      out.push({
        ...common,
        kind: 'crypto',
        symbol: data.symbol,
        coingeckoId: data.coingeckoId,
        name: data.name ?? data.symbol,
        entryPrice: lock.entryPrice,
        ...(lock.exitPrice != null ? { exitPrice: lock.exitPrice } : {}),
      })
    } else if (data.kind === 'private') {
      if (data.entryValuation == null || data.currentValuation == null) {
        missing.push(`${id} (private valuations)`)
        continue
      }
      out.push({
        ...common,
        kind: 'private',
        name: data.name,
        entryValuation: data.entryValuation,
        currentValuation: data.currentValuation,
        ...(data.exitValuation != null ? { exitValuation: data.exitValuation } : {}),
      })
    }
  }

  out.sort((a, b) => (a.entryDate < b.entryDate ? 1 : -1))

  const code =
    `// generated by scripts/build-positions.ts — do not edit\n` +
    `import type { Position } from './types'\n\n` +
    `export const positions: Position[] = ${JSON.stringify(out, null, 2)}\n`
  await fs.writeFile(GENERATED_FILE, code)

  if (missing.length > 0) {
    console.warn(`! ${missing.length} position(s) skipped — fix and run \`bun run prices:resolve\` if needed:`)
    for (const m of missing) console.warn(`  - ${m}`)
  }
  console.log(`✓ generated ${out.length} position(s)`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
